

CINCLUDE_FILE += catOS/src/components/cat_error
CINCLUDE_FILE += catOS/src/components/cat_sys_print
CINCLUDE_FILE += catOS/src/drivers/uart
CINCLUDE_FILE += catOS/src/support
CINCLUDE_FILE += catOS/user/bsp/uart


obj-y += cat_shell_cmds.o
obj-y += cat_shell_port.o
obj-y += cat_shell.o

include $(RULE_DIR)/rules.mk
